### ISSUE TITLE
It behaves differently when size change or location changed.

### ISSUE THREAD

**Issue by IamAliSufyan** [dainkaplan/Chartreuse#3]
I am newbie in IOS dev. I am using your Pie chart in my app but its not getting right. When i draw UIView of small size it does not show, If want 200x200 chart it enforces me to draw a 240x400. Its behaves different on different sizes and location, some times draws a shadow bottom-side some time topside. Please Help!

**Comment by dainkaplan** [comment]
I think this has been fixed in the most recent merge, thanks to contributions.
